apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cast
  labels:
    app: {{ .Release.Name }}-cast
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-cast
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-cast
    spec:
      containers:
        - name: cast
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

