apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-cast-service-claim0
  labels:
    app: {{ .Release.Name }}-cast-service
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.castService.pvc.storage }}

