apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: cast-db
  name: {{ .Release.Name }}-cast-db
spec:
  replicas: {{ .Values.castDb.replicaCount }}
  selector:
    matchLabels:
      io.kompose.service: cast-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.service: cast-db
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: {{ .Values.castDb.database }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.castDb.password }}
        - name: POSTGRES_USER
          value: {{ .Values.castDb.username }}
        image: postgres:12.1-alpine
        imagePullPolicy: IfNotPresent
        name: cast-db
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/
          name: postgres-data-cast
      volumes:
      - name: postgres-data-cast
        persistentVolumeClaim:
          claimName: postgres-data-cast

