apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jenkex.fullname" . }}
  labels:
    {{ include "jenkex.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{ include "jenkex.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "jenkex.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "jenkex.name" . }}
         
          ports:
            - containerPort: {{ .Values.containerPort | default 8000 }}
