apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-movie-service
  labels:
    io.kompose.service: movie-service
spec:
  replicas: {{ .Values.movieService.replicaCount }}
  selector:
    matchLabels:
      io.kompose.service: movie-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: movie-service
    spec:
      containers:
      - args:
        - uvicorn
        - app.main:app
        - --host
        - 0.0.0.0
        - --port
        - "8000"
        env:
        - name: DATABASE_URI
          value: postgresql://{{ .Values.movieDb.username }}:{{ .Values.movieDb.password }}@{{ .Release.Name }}-movie-db/{{ .Values.movieDb.database }}
        image: {{ .Values.movieService.image.repository }}:{{ .Values.movieService.image.tag }}
        imagePullPolicy: IfNotPresent
        name: movie-service
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /app/
