apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-movie-service-claim0
  labels:
    app: {{ .Release.Name }}-movie-service
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.movieService.pvc.storage }}

