# Default values for your application
replicaCount: 1

castDb:
  database: cast_db_dev
  username: eltemume_cast_db_user
  password: cast_db_password
  replicaCount: 1

movieDb:
  database: movie_db_dev
  username: eltemume_movie_db_user
  password: movie_db_password
  replicaCount: 1

castService:
  image:
    repository: eltemume/cast-service
    tag: latest
  replicaCount: 1

movieService:
  image:
    repository: eltemume/movie-service
    tag: latest
  replicaCount: 1

# Additional settings and configurations can go here

